apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-in-one
  namespace: aio
  labels:
    app: myaio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myaio
  template:
    metadata:
      labels:
        app: myaio
    spec:
      containers:
      - name: usomgupta
        image: usomgupta/fedora-github-all-in-one:v3
        #ports:
        #- containerPort: 80
        #resources:
        #  requests:
        #    cpu: "100m"