apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-in-one-deployment
  labels:
    app: all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: all-in-one
  template:
    metadata:
      labels:
        app: all-in-one
    spec:
      containers:
      - name: all-in-one
        image: usomgupta/all-in-one:23.20.06
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "10m"